## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN T17 [get_ports pb_start]
set_property IOSTANDARD LVCMOS33 [get_ports pb_start]

# increase decrease
set_property PACKAGE_PIN T18 [get_ports {pb_inc}]
set_property IOSTANDARD LVCMOS33 [get_ports {pb_inc}]
set_property PACKAGE_PIN U17 [get_ports {pb_dec}]
set_property IOSTANDARD LVCMOS33 [get_ports {pb_dec}]

set_property PACKAGE_PIN V17 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]


##VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vgaRed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBlue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBlue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBlue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
set_property PACKAGE_PIN J18 [get_ports {vgaBlue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

#keyboard
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]


set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[0]}]
set_property PACKAGE_PIN W4 [get_ports {ssd_ctl[3]}]
set_property PACKAGE_PIN V4 [get_ports {ssd_ctl[2]}]
set_property PACKAGE_PIN U4 [get_ports {ssd_ctl[1]}]
set_property PACKAGE_PIN U2 [get_ports {ssd_ctl[0]}]

#ssd_out
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[7]}]
set_property PACKAGE_PIN W7 [get_ports {ssd_out[7]}]
set_property PACKAGE_PIN W6 [get_ports {ssd_out[6]}]
set_property PACKAGE_PIN U8 [get_ports {ssd_out[5]}]
set_property PACKAGE_PIN V8 [get_ports {ssd_out[4]}]
set_property PACKAGE_PIN U5 [get_ports {ssd_out[3]}]
set_property PACKAGE_PIN V5 [get_ports {ssd_out[2]}]
set_property PACKAGE_PIN U7 [get_ports {ssd_out[1]}]
set_property PACKAGE_PIN V7 [get_ports {ssd_out[0]}]

# Pmod I2S
set_property PACKAGE_PIN A14 [get_ports {mclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {mclk}]
set_property PACKAGE_PIN A16 [get_ports {lrck}]
set_property IOSTANDARD LVCMOS33 [get_ports {lrck}]
set_property PACKAGE_PIN B15 [get_ports {sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {sclk}]
set_property PACKAGE_PIN B16 [get_ports {audio_sdin}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_sdin}]

set_property IOSTANDARD LVCMOS33 [get_ports {level_display[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {level_display[0]}]
set_property PACKAGE_PIN L1 [get_ports {level_display[15]}]
set_property PACKAGE_PIN P1 [get_ports {level_display[14]}]
set_property PACKAGE_PIN N3 [get_ports {level_display[13]}]
set_property PACKAGE_PIN P3 [get_ports {level_display[12]}]
set_property PACKAGE_PIN U3 [get_ports {level_display[11]}]
set_property PACKAGE_PIN W3 [get_ports {level_display[10]}]
set_property PACKAGE_PIN V3 [get_ports {level_display[9]}]
set_property PACKAGE_PIN V13 [get_ports {level_display[8]}]
set_property PACKAGE_PIN V14 [get_ports {level_display[7]}]
set_property PACKAGE_PIN U14 [get_ports {level_display[6]}]
set_property PACKAGE_PIN U15 [get_ports {level_display[5]}]
set_property PACKAGE_PIN W18 [get_ports {level_display[4]}]
set_property PACKAGE_PIN V19 [get_ports {level_display[3]}]
set_property PACKAGE_PIN U19 [get_ports {level_display[2]}]
set_property PACKAGE_PIN E19 [get_ports {level_display[1]}]
set_property PACKAGE_PIN U16 [get_ports {level_display[0]}]
